dare2ask/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from dare2ask import views

app_name = 'dare2ask'
urlpatterns = [
	url(r'^$',
		views.index, name='index'),
	url(r'^about/$',
		views.about, name='about'),
	url(r'^lecture/$',
		views.lecture, name='lecture'),
	url(r'^lecture/(?P<lecture_name_slug>[\w\-]+)/$',
		views.in_lecture, name='in_lecture'),
	url(r'^search/(?P<search_slug>[\w\-]+)$',
		views.search, name = 'search'),
	url(r'^delete/(?P<lecture_name_slug>[\w\-]+)/(?P<question_id>\d+)$',
		views.delete_Q, name = 'delete_Q'),
	url(r'^delete/(?P<lecture_name_slug>[\w\-]+)/confirm$',
		views.delete_conf, name = 'delete_conf'),
	url(r'^delete/(?P<lecture_name_slug>[\w\-]+)/$',
		views.delete, name = 'delete'),
	url(r'^register_profile/$',
		views.register_profile, name='register_profile'),
	url(r'^profile/(?P<username>[\w\-]+)/$',
		views.profile, name='profile'),
	url(r'^like/$', views.like_question, name='like_question'), # temporary like id for AJAX - EF
]

dare_2_ask_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from dare2ask import views
from registration.backends.simple.views import RegistrationView

# New class that redirects the user to the index page if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/dare2ask/register_profile'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^dare2ask/', include('dare2ask.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views
from registration.backends.simple.views import RegistrationView

# New class that redirects the user to the index page if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dare2ask/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Lecturers can create lectures. Within, questions can be interacted with.
class Lecture(models.Model):
    title = models.CharField(max_length=128, unique = True)
    join_ID = models.IntegerField(default = -1)
    course_num = models.CharField(max_length=128, default = -1)

    slug = models.SlugField(unique = True) # (blank = True)
    max_length = 128

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Lecture, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class Search(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(unique = False) # (blank = True)

    def __str__(self):
        return self.name

# For the questions that will be polled from students within a lecture.
class Question(models.Model):
    # Holds parent Lecture, one-to-many relationship
    lecture = models.ForeignKey(Lecture)
    text = models.CharField(max_length=128)
    upvotes = models.IntegerField(default = 0)
    answered = models.BooleanField(default = False)
    max_length=128

    def __str__(self):
        return self.text

# Detailed
class UserProfile(models.Model):
	# This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

	# The additional attributes we wish to include
    picture = models.ImageField(upload_to='profile_images', blank=True, default='../static/images/default.png')
    lecturer = models.BooleanField(default = False)

	# Override the __unicode__() method to return out something meaningful!
    def __str__(self):
	    return self.user.username

dare2ask/forms.py
from django import forms
from django.contrib.auth.models import User
from dare2ask.models import Lecture, Question, Search
from dare2ask.models import UserProfile

class LectureForm(forms.ModelForm):
    title = forms.CharField(max_length=Lecture.max_length,
                required=True,
                widget=forms.TextInput(attrs={
                            'class':'form-control',
                            'placeholder':"Lecture title...",
                            'name':'title'
                            } ) )
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline metaclass to provide addiional info on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Lecture
        fields = ('title',)

class SearchForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                help_text="Please enter the name of the \
                    lecture you are looking for.",
                required=True)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline metaclass to provide addiional info on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Search
        fields = ('name',)

class QuestionForm(forms.ModelForm):
    text = forms.CharField(max_length=Question.max_length, help_text="Please enter your question.")
    #lecture = Lecture.objects.filter(title="abc")

    class Meta:
        model = Question
        fields = ('text', )


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    # is_staff = forms.BooleanField(widget=forms.CheckboxInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'is_staff')

class UserProfileForm(forms.ModelForm):
    picture = forms.ImageField(required=False)
    lecturer = forms.BooleanField(widget=forms.CheckboxInput(), required=False)

    class Meta:
	    model = UserProfile
	    exclude = ('user', )

dare2ask/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User

from dare2ask.models import Lecture, UserProfile, Question
from dare2ask.forms import LectureForm, SearchForm, QuestionForm
from dare2ask.forms import UserForm, UserProfileForm
from dare2ask.decorators import is_staff

from datetime import datetime

def index(request):
	request.session.set_test_cookie()

	visitor_cookie_handler(request)

	context_dict = {}
	# Obtain our response object early so we can add cookie info
	response = render(request, 'dare2ask/index.html', context=context_dict)

	# Return response back to the user, updating any cookies that needed change
	return response

def about(request):
#	if request.session.test_cookie_worked():
#		print("TEST COOKIE WORKED!")
#		request.session.delete_test_cookie()

	context_dict = {}

	visitor_cookie_handler(request)

	return render(request, 'dare2ask/about.html', context=context_dict)

@login_required
def lecture(request):
    formLec = LectureForm()
    context_dict = {}

    # A HTTP Post?
    if request.method == 'POST':
        if 'lecture' in request.POST:
        	formLec = LectureForm(request.POST)

	        # Have we been provided with a valid form?
	        if formLec.is_valid():
	            # Save the new category to the database.
	            lec = formLec.save(commit=True)
	            # Now that the lecture is saved
	            # We could give a confirmation message
	            # Bit since he most recent category added is on the index page
	            # Then we can direct the user back to the index page.
	            print(formLec.cleaned_data)
	            return redirect('/dare2ask/lecture/' +
	                (formLec.cleaned_data)['title'] )

	        else:
	            # The supplised form contained errors,
	            # Print errors to terminal.
	            print(formLec.errors)

    elif request.method == 'GET':
	    if 'search' in request.GET:
	        lecs = Lecture.objects.order_by('title')
	        search_slug = request.GET['search']
	        print(lecs)
	        print(search_slug)
	        print(request.GET)
	        lecs = lecs.filter(title__icontains=search_slug)
	        print(lecs)
	        context_dict = {'lectures': lecs, 'search': search_slug}
	        # formLec = SearchForm(request.GET)
			#
	        # # Have we been provided with a valid form?
	        # if formLec.is_valid():
	        #     print(formLec.cleaned_data)
	        return render(request, 'dare2ask/search.html', context_dict)
			#
	        # else:
		    #     # The supplised form contained errors,
		    #     # Print errors to terminal.
	        #     print(formLec.errors)

    # Check that lectures exist
    try:
        lecture_list = Lecture.objects.order_by('-title')
        context_dict['lectures'] = lecture_list
    except Lecture.DoesNotExist:
        context_dict['lectures'] = None

    context_dict['form'] = formLec

    # Will handle the bad form, new form, or no form supplied cases
    # Will render the form with error messages
    return render(request, 'dare2ask/lecture.html', context_dict)

@login_required
def search(request, search_slug):
	print(search_slug)
	for lec in Lecture.objects.order_by('title'):
		# if search_slug in
		print(lec)
	return HttpResponse("Hello")

@login_required
def in_lecture(request, lecture_name_slug):
	form = QuestionForm()
	context_dict = {'form': form}
	try:
		# Look for lecture name slug with given name.
		# If not found, raise DoesNotExist exception.
		# So the .get() method returns one model instance or
		# raises an exception.
		lecture = Lecture.objects.get(slug = lecture_name_slug)

		# Retrieve all of the associated questions.
		# filter() will return a list of question objects or empty list
		questions = Question.objects.filter(lecture = lecture)

		# Adds our results list to the template context under name pages.
		context_dict['questions'] = questions

		# We also add the lecture object from the DB to the context
		# dictionary. We'll use this in the template to verify that
		# the lecture exists.
		context_dict['lecture'] = lecture
	except Lecture.DoesNotExist:
		# We get here if we didn't find the specified category
		# Template will display "no category" message
		context_dict['lecture'] = None

	# To interact with questions
	if request.method == 'POST':
		print("REQUEST=",request.body,"\n",request.POST)
		if "Create Question" in request.POST.get('create_question', 'None'):
			form = QuestionForm(request.POST)
			if form.is_valid():
				q = form.save(commit=False)
				q.lecture = context_dict['lecture']
				q.save()
				return HttpResponseRedirect('/dare2ask/lecture/' + lecture_name_slug)
			else:
				print(form.errors)
				return HttpResponseRedirect('/dare2ask/lecture/' + lecture_name_slug)

		elif "answered_question" in request.POST:
			i = int(request.POST['answered_question'])-1
			question = context_dict["questions"][i]
			if question.answered == True:
				question.answered = False
			else:
				question.answered = True
			question.save()
			return HttpResponseRedirect('/dare2ask/lecture/' + lecture_name_slug)
		else:
			print("UNRECOGNIZED")
			return HttpResponseRedirect('/dare2ask/lecture/' + lecture_name_slug)

	return render(request, 'dare2ask/in_lecture.html', context=context_dict)

@login_required
def delete_conf(request, lecture_name_slug):
    context_dict = {}

    try:
        lecture = Lecture.objects.get(slug = lecture_name_slug)

        context_dict['lecture'] = lecture

    except Lecture.DoesNotExist:
        context_dict['lecture'] = None
        print('context_dict["lecture"]= None')
    return render(request, 'dare2ask/delete_conf.html', context_dict)

@login_required
def delete(request, lecture_name_slug):
    lec = get_object_or_404(Lecture, slug = lecture_name_slug).delete()
    return HttpResponseRedirect('/dare2ask')

@login_required
def delete_Q(request, lecture_name_slug, question_id):
	lecture = Lecture.objects.get(slug = lecture_name_slug)

	# Retrieve all of the associated questions.
	# filter() will return a list of question objects or empty list
	# qAll = Question.objects.all()
	# print(qAll)
	# questions = Question.objects.filter(lecture = lecture)

	# print(questions)
	Question.objects.filter(id = question_id).delete()
	questions2 = Question.objects.filter(lecture = lecture)
	# print(questions2)
	return HttpResponseRedirect('/dare2ask/lecture/' + lecture_name_slug)

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
	val = request.session.get(cookie)
	if not val:
		val = default_val
	return val

def visitor_cookie_handler(request):
	visits = int(get_server_side_cookie(request, 'visits', '1'))

	last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
	last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

	# If it's been more than a day since the last visit:
	if (datetime.now() - last_visit_time).days > 0:
		visits = visits + 1
		# Update the last visit cookie
		request.session['last_visit'] = str(datetime.now())
	else:
		# Set the last visit cookie
		request.session['last_visit'] = last_visit_cookie

	# Update/set the visits cookie
	request.session['visits'] = visits

@login_required
def register_profile(request):
	form = UserProfileForm()
	if request.method == 'POST':
		form = UserProfileForm(request.POST, request.FILES)
		if form.is_valid():
			user_profile = form.save(commit=False)
			user_profile.user = request.user
			user_profile.save()
			# if form.lecturer:
			# 	userprofile.lecturer = True

			return redirect('index')
		else:
			print(form.errors)

	context_dict = {'form':form}

	return render(request, 'dare2ask/profile_registration.html', context_dict)

@login_required
def profile(request, username):
	try:
		user = User.objects.get(username=username)
	except User.DoesNotExist:
		return redirect('index')

	userprofile = UserProfile.objects.get_or_create(user=user)[0]
	form = UserProfileForm(
		{'picture': userprofile.picture, 'lecturer': userprofile.lecturer})

	if request.method == 'POST':
		form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
		if form.is_valid():
			form.save(commit=True)
			return redirect('dare2ask:profile', user.username)
		else:
			print(form.errors)

	return render(request, 'dare2ask/profile.html',
		{'userprofile': userprofile, 'selecteduser': user, 'form': form})


@login_required
def like_question(request):
	l_id = None; # l_id == like_id
	if request.method == 'GET':
		l_id = request.GET['like_id'];  # getting "like_id" from the button in ajax.js
		likes = 0;
		all_likes = ""
		if l_id:
			q = Question.objects.get(id=int(l_id));
			if q:
				likes = q.upvotes + 1;
				q.upvotes = likes;
				q.save();
				# Get parent lecture of question
				l = q.lecture
				# Get all questions with this parent lecture
				all_qs = Question.objects.filter(lecture=l)
				for n in all_qs:
					print(n.upvotes)
					all_likes += str(n.upvotes)
					all_likes += " "
	return HttpResponse(all_likes)

templates/dare2ask/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load dare2ask_template_tags %}

<!-- To do list:
  - Make everything actually pretty using CSS
-->

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'images/favicon.ico' %}">

  <!-- Styling css links here: -->

  <link rel="stylesheet" type="text/css" href="{% static 'css/core.css' %}">
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}"> -->
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/styling.css' %}">

  <!-- End of styling sheet links -->
  <title>
    {% block title_block %}
      BASE TITLE
    {% endblock %}
  </title>
  <!-- Bootstrap core CSS -->
  <!-- <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet"> -->
  <!-- Custom styles for this template -->
  <!-- <link href= "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet"> -->
  <!-- <link href= "http://v4-alpha.getbootstrap.com/examples/product/product.css" rel="stylesheet"> -->
</head>

<body style="background-image: url('../../static/images/background.png'), url('../../../static/images/background.png')">

<nav class="site-header sticky-top py-1">
  <div class="container d-flex flex-column flex-md-row justify-content-between">
    <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/Logo.png' %}" width="82"></a>
    {% if user.is_authenticated %}
    <a class="py-2 d-none d-md-inline-block" href="{% url 'dare2ask:profile' user.username %}" style="margin-top: 25px">Logged in as: {{ user.username }}           <img src="{{ MEDIA_URL }}{{user.userprofile.picture }}" width="30" height="30"> </a>
    <a class="py-2 d-none d-md-inline-block" href="{% url 'dare2ask:lecture' %}" style="margin-top: 25px">
      {% if user.userprofile.lecturer %}
        Create or join a lecture
      {% else %}
        Join a lecture
      {% endif %}
    </a>
    <a class="py-2 d-none d-md-inline-block" href="{% url 'auth_logout' %}?next=/dare2ask/" style="margin-top: 25px">Logout</a>
    {% else %}
    <a class="py-2 d-none d-md-inline-block" href="{% url 'registration_register' %}" style="margin-top: 25px">Register Here</a>
    <a class="py-2 d-none d-md-inline-block" href="{% url 'auth_login' %}" style="margin-top: 25px">Login</a>
    {% endif %}
    <a class="py-2 d-none d-md-inline-block" href="{% url 'dare2ask:about' %}" style="margin-top: 25px">About</a>
  </div>
</nav>

<div style="margin:auto; text-align: center;">
  <div style="margin-top: 25px">
    <h1 class="display-4 font-weight-normal">{% block header %}DEFAULT HEADER{%endblock%}</h1>
    <p>{% block headertext %} DEFAULT HEADERTEXT{%endblock%}</p>
  </div>
</div>

<div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
  <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">{%block headerlowleft %} LOW LEFT HEADER {% endblock %}</h2>
      <p class="lead">{%block textlowleft %} LOW LEFT TEXT {% endblock %}</p>
    </div>
    <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
  <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">{%block headerlowright %} LOW RIGHT HEADER {% endblock %}</h2>
      <p class="lead">{%block textlowright %} LOW RIGHT TEXT {% endblock %}</p>
    </div>
    <div class="bg-dark shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
  </div>
</div>

<!-- Bootstrap core JavaScript ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
    </script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
    </script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src= "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
    </script>
    <!-- <script src="{% static "js/jquery.min.js" %}"></script> -->
    <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "js/dare2ask-ajax.js" %}"></script>

</body>
</html>

templates/dare2ask/delete_conf.html
<!DOCTYPE html>

{% extends 'dare2ask/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {% if lecture.title %}
    Delete {{ lecture.title }}
  {% else %}
    Lecture not found
  {% endif %}
{% endblock %}

{% block header %}
  {% if lecture.title %}
    <h1>Delete {{ lecture.title }}</h1>
  {% else %}
    <h1>Lecture not found!</h1>
  {% endif %}
{% endblock %}
{% block headertext %}
  {% if lecture.title %}
    <div>
      Are you sure you want to delete the lecture, [{{ lecture.title }}]? <br/>
      <button class="button1" onclick="window.location.href =
        '/dare2ask/delete/{{lecture.slug}}';">Delete!</button>
      <button class="button1" onclick="window.location.href =
          '/dare2ask/lecture/{{lecture.slug}}';">No!</button>
    </div>
  {% else %}
    <div>
      Can't delete a lecture that doesn't exist!</br>
      <a href = "{% url 'dare2ask:lecture' %}">Try another </a>
    </div>
  {% endif %}
{% endblock %}

{% block headerlowleft %}
{% endblock %}
{% block textlowleft %}
{% endblock %}
{% block headerlowright %}
{% endblock %}
{% block textlowright %}
{% endblock %}

templates/dare2ask/in_lecture.html
<!DOCTYPE html>

<script>
function removeQ(id) {
  document.getElementById("demo").innerHTML = "Hello World";
}
</script>

{% extends 'dare2ask/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {% if lecture.title %}
    Lecture: {{ lecture.title }}
  {% else %}
    Lecture not found
  {% endif %}
{% endblock %}

{% block header %}
  {% if lecture.title %}
    {{ lecture.title }}
  {% else %}
    Lecture not found!
  {% endif %}
{% endblock %}
{% block headertext %}
  {% if lecture.title %}
    <div>
      <form id="question_form" method="post"
        action="{% url 'dare2ask:in_lecture' lecture.slug %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
          {{ field.errors }}
          {{ field.help_text}}
          {{ field }}
        {% endfor %}
        <input class="button1" type="submit" name="create_question" value="Create Question" />
      </form>
    </div>
    <br/>
    <div>
      {% if questions %}
        <h3>Questions:</h3>
          {% for question in questions %}
          <div class="reglog_input lecturer_buttons">
              <a style="font-style: italic; font-size: 20px; background-color: yellow;">
                {% if question.answered %}
                  <a.ans style="background-color: #ccc;">
                {% endif %}
                  "{{ question.text }}"
                </a.ans>
                <br/>
              </a>

              <!--
              <br>Votes: {{ question.upvotes }}
               Upvote form only visible to students
              <form id="upvote" method="post" action="{% url 'dare2ask:in_lecture' lecture.slug %}">
                {% csrf_token %}
                <button type="submit" value="{{forloop.counter}}" name="upvote_question">Upvote</button>
              </form>
            -->

            <!-- AJAX button goes here -->
              <strong class="like_count" style="padding-right: 10px">
                {{ question.upvotes }}
              </strong>
              {% if not user.userprofile.lecturer %}
                <button data-upvoteid="{{question.id}}" class="button1 likes" type="button">
                  Like
                </button>
              {% endif %}
            <!-- END ajax button -->
              
              <a style="color: grey;">
                |
                {% if question.answered %} 
                  Answered
                {% else %} 
                  Unanswered
                {% endif %}
              </a>

              <!-- Answered form only visible to instructors -->
              {% if user.userprofile.lecturer %}
                <form class="lecturer" id="answered" method="post" action="{% url 'dare2ask:in_lecture' lecture.slug %}">
                  {% csrf_token %}
                  <button class="button1" type="submit" name="answered_question" value="{{forloop.counter}}">
                    Mark
                    {% if question.answered %} 
                      Unanswered
                    {% else %} 
                      Answered
                    {% endif %}
                  </button>
                </form>

                <!-- Delete question button -->
                <button class="button1 lecturer" onclick="window.location.href =
                '/dare2ask/delete/{{lecture.slug}}/{{question.id}}';">
                  Delete
                </button>

              {% endif %}
              </div>
              <br/><br/><br/>
          {% endfor %}

      {% else %}
        <div>No questions have been asked</div>
      {% endif %}
    </div>
  {% else %}
    <div>
      A lecture with this name does not exist. </br>
      <a href = "{% url 'dare2ask:lecture' %}">Try another </a>
    </div>
  {% endif %}
{% endblock %}

{% block headerlowleft %}
{% endblock %}
{% block textlowleft %}
{% endblock %}

<!-- Delete the lecture -->
{% block headerlowright %}
  {% if lecture.title %}
    {% if user.userprofile.lecturer %}
      <h1>Delete the lecture!</h1>
    {% endif %}
  {% endif %}
{% endblock %}

{% block textlowright %}
  {% if lecture.title %}
    {% if user.userprofile.lecturer %}
      <button class="button1" onclick="window.location.href =
        '/dare2ask/delete/{{lecture.slug}}/confirm';">Delete!</button>
    {% endif %}
  {% endif %}
{% endblock %}

templates/dare2ask/index.html
<!DOCTYPE html>

{% extends 'dare2ask/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Dare2Ask!
{% endblock %}

{% block header %}
<div>
	<ul>
		{% if user.is_authenticated %}
			<h1>Hi, {{user}}! </br> </h1>
		{% endif %}
		<p>Welcome to Dare2Ask!</p><br />
	</ul>
</div>
{% endblock %}
{% block headertext %}
{% if user.is_authenticated %}
	<div class="buttonsIndex">
	<button onclick="window.location.href = '{% url 'dare2ask:lecture' %}'" class="button1">
	{% if user.userprofile.lecturer %}
		Create or Join a Lecture
	{% else %}
		Join a Lecture
	{% endif %}
	</button>
	<!--<a href="{% url 'auth_logout' %}?next=/dare2ask/" class=button1>Logout</a> -->
{% else %}
	<button onclick="window.location.href='{% url 'registration_register' %}'" class="button1"> Register with us to get started!</button>
</div>
{% endif %}
{% endblock %}
{% block headerlowleft %}
{% endblock %}
{% block textlowleft %}
{% endblock %}
{% block headerlowright %}
{% endblock %}
{% block textlowright %}
{% endblock %}

templates/dare2ask/profile_registration.html
<!DOCTYPE html>

{% extends 'dare2ask/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Registration - Step 2
{% endblock %}
<link href="http"//v4-alpha.getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
{% block header %}
<div class="reglog_banner">
		<h1 class="reglog_text">Register - Step 2</h1>
	</div>
{% endblock %}
{% block headertext %}
	<form method="post" action="." enctype="multipart/form-data">
		{% csrf_token %}
		<div class="reglog_input">
		{% for field in form.visible_fields %}
			<a class="fieldname">{{field.name}} :</a> {{ field }}
		{% endfor %}
		</div>
		<br/>
		<input type="submit" value="Submit or skip" class="button1" />
	</form>
{% endblock %}
{% block headerlowleft %}
{% endblock %}
{% block textlowleft %}
{% endblock %}
{% block headerlowright %}
{% endblock %}
{% block textlowright %}
{% endblock %}